# Generated by Django 5.0.6 on 2024-08-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('Prize', models.IntegerField()),
                ('Description', models.TextField()),
                ('src', models.TextField()),
                ('star', models.IntegerField(max_length=5)),
            ],
        ),
    ]
