# Generated by Django 5.0.6 on 2024-08-18 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitable', '0002_alter_food_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Prize',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='food',
            name='src',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='food',
            name='star',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
